### ISSUE TITLE
Typography for Font Parsing and Text Rendering 

### ISSUE THREAD

**Issue by prepare** [Myvar/CosmosGL#3]
Hello, 

I just want to introduce another
a Pure C# Font Parsing and Rendering 
=> here the [Typography](https://github.com/LayoutFarm/Typography) Lib.

It may help you parse a font file (ttf, otf) , do _OpenType_ layout.

and It lets you draw each glyph by your own.

**Comment by Myvar** [comment]
I already implmented ttf parsing, and rendering, the quality is not the best, but its progress.
